### ISSUE TITLE
auto-completion plugin is causing some problems with the new intelligent patching feature in 0.49

### ISSUE THREAD

**Issue by LGoodacre** [HenriAugusto/completion-plugin#14]
Unfortunately, there seems to be some conflict between your plugin and the new intelligent patching features in 0.49.

See [this](https://1drv.ms/u/s!AvOKHMTdUCc2xGdvwrkbXCpnSRX6), and [this](https://github.com/pure-data/pure-data/issues/444#issuecomment-420392187) other issue report.

**Comment by HenriAugusto** [comment]
I literaly just fixed that this minute :)

Since [the redundant edit->preferences was removed on windows/linux](https://github.com/HenriAugusto/completion-plugin/issues/13) TCL throws this errors.

The next release (0.46.0) already fixes that. I just uploaded it to deken so it will be available soon :)

**Comment by LGoodacre** [comment]
Great!
