### ISSUE TITLE
Request: add a second "auto complete library names" option for monolithic searches

### ISSUE THREAD

**Issue by LGoodacre** [HenriAugusto/completion-plugin#2]
It would be useful if there were options in the settings menu: one for auto-completing library names for normal searches and one for auto-completing library names for monolithic searches. I have the practice of specifying library names with normal libraries (ie. iemguts) but not with monolithic ones (ie. zexy). But it currently doesn't seem possible to cater to this without editing the preferences every time.

**Comment by LGoodacre** [comment]
Or another option: Ctrl+click adds the library name, normal click doesn't.

**Comment by HenriAugusto** [comment]
I'm not sure i understand what is happening.

What is supposed to happen:

*auto complete library names is **on** *: 
- normal abstractions will have their library name, like [cyclone/counter]
- objects contained in multi-object ("monolithic") libraries will **not** have their names auto completed

*auto complete library names is **off** *: 
- normal abstractions will have their library name, like [counter]
- objects contained in multi-object ("monolithic") libraries will **not** have their names auto completed

The reason for externals contained in multi-object files to not have their library autocomplete is because they must be loaded into memory. You actually **can't** instantiate them by using the library name.

![zexy 1](https://user-images.githubusercontent.com/11790621/44435441-6300d600-a586-11e8-8cab-3be7b42d57d1.png)

Which is, IMO, a serious issue with Pure Data external loading mechanism as you can't avoid naming conflicts!

What exactly are you doing that makes you need to go to the settings every time?

**Comment by LGoodacre** [comment]
Looks like I got off on the wrong foot here. It might be best to forget everything I said and start again.

It seems that the plugin isn't finding objects from monolithic libraries on my Linux machine. Ie. when I search for "demux" nothing comes, even once Zexy is loaded. If I search for "zexy", I find only those objects which are actually abstractions, like [zexy/l2i], or the ones which have terrible names like [zexy/0x260x260x7e].

![zexy](https://user-images.githubusercontent.com/22167643/44468074-7454eb80-a635-11e8-9500-f30369cf1136.png)


I think that was happening previously was that it was finding a precompiled version of demux.pd_linux which was sitting in folder which was sitting inside one of the search paths. It then added "zexy/" because it thought it was a regular external. But now that I've removed these anomalous objects, I'm back to the situation described above.

Is there something I've missed which I'm supposed to do in order to search for monolithic objects?

**Comment by HenriAugusto** [comment]
Just like for *skipping* search you start your serach with a "**.**" (period), for searching objects contained in multi-object ("monolithic") distributions you start your serach with a "**,**" (comma).

Note that the objects shown are defined in a file in

`completion-plugin/monolithics_objects/monolithicLibs.txt`

Right know it already contains some stuff i've added so it might show you some objects you don't have.

I've already created and issue for that. Issue #5

**Comment by HenriAugusto** [comment]
It's okay :)

I did rework on the gif and i hope it's better now. Also i've renamed that help patch to README.deken.pd so it will open automatically when you download it from Deken. I've also planned adding a *help* button on the settings menu for the next release (Issue #6)
